In [11]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [12]:
DATA_PATH = r"D:\MLOPS\data\raw"

In [13]:
DATA_PATH

'D:\\MLOPS\\data\\raw'

In [14]:
monday = pd.read_csv(
    rf"{DATA_PATH}\Monday-WorkingHours.pcap_ISCX.csv"
)

In [15]:
type(monday)

pandas.DataFrame

In [16]:
monday.shape

(529918, 79)

In [17]:
monday.head(5)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,49188,4,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,3000000.0,5.000000e+05,4.0,0.0,4,4,4,4.0,0.0,4,4,0,0.0,0.0,0,0,0,0,0,0,40,0,5.000000e+05,0.0,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,329,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,49188,1,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,12000000.0,2.000000e+06,1.0,0.0,1,1,1,1.0,0.0,1,1,0,0.0,0.0,0,0,0,0,0,0,40,0,2.000000e+06,0.0,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,329,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,49188,1,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,12000000.0,2.000000e+06,1.0,0.0,1,1,1,1.0,0.0,1,1,0,0.0,0.0,0,0,0,0,0,0,40,0,2.000000e+06,0.0,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,329,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,49188,1,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,12000000.0,2.000000e+06,1.0,0.0,1,1,1,1.0,0.0,1,1,0,0.0,0.0,0,0,0,0,0,0,40,0,2.000000e+06,0.0,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,329,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,49486,3,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,4000000.0,6.666667e+05,3.0,0.0,3,3,3,3.0,0.0,3,3,0,0.0,0.0,0,0,0,0,0,0,40,0,6.666667e+05,0.0,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,245,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [18]:
monday.columns.tolist()

[' Destination Port',
 ' Flow Duration',
 ' Total Fwd Packets',
 ' Total Backward Packets',
 'Total Length of Fwd Packets',
 ' Total Length of Bwd Packets',
 ' Fwd Packet Length Max',
 ' Fwd Packet Length Min',
 ' Fwd Packet Length Mean',
 ' Fwd Packet Length Std',
 'Bwd Packet Length Max',
 ' Bwd Packet Length Min',
 ' Bwd Packet Length Mean',
 ' Bwd Packet Length Std',
 'Flow Bytes/s',
 ' Flow Packets/s',
 ' Flow IAT Mean',
 ' Flow IAT Std',
 ' Flow IAT Max',
 ' Flow IAT Min',
 'Fwd IAT Total',
 ' Fwd IAT Mean',
 ' Fwd IAT Std',
 ' Fwd IAT Max',
 ' Fwd IAT Min',
 'Bwd IAT Total',
 ' Bwd IAT Mean',
 ' Bwd IAT Std',
 ' Bwd IAT Max',
 ' Bwd IAT Min',
 'Fwd PSH Flags',
 ' Bwd PSH Flags',
 ' Fwd URG Flags',
 ' Bwd URG Flags',
 ' Fwd Header Length',
 ' Bwd Header Length',
 'Fwd Packets/s',
 ' Bwd Packets/s',
 ' Min Packet Length',
 ' Max Packet Length',
 ' Packet Length Mean',
 ' Packet Length Std',
 ' Packet Length Variance',
 'FIN Flag Count',
 ' SYN Flag Count',
 ' RST Flag Count',
 ' PSH Flag Count',
 ' ACK Flag Count',
 ' URG Flag Count',
 ' CWE Flag Count',
 ' ECE Flag Count',
 ' Down/Up Ratio',
 ' Average Packet Size',
 ' Avg Fwd Segment Size',
 ' Avg Bwd Segment Size',
 ' Fwd Header Length.1',
 'Fwd Avg Bytes/Bulk',
 ' Fwd Avg Packets/Bulk',
 ' Fwd Avg Bulk Rate',
 ' Bwd Avg Bytes/Bulk',
 ' Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate',
 'Subflow Fwd Packets',
 ' Subflow Fwd Bytes',
 ' Subflow Bwd Packets',
 ' Subflow Bwd Bytes',
 'Init_Win_bytes_forward',
 ' Init_Win_bytes_backward',
 ' act_data_pkt_fwd',
 ' min_seg_size_forward',
 'Active Mean',
 ' Active Std',
 ' Active Max',
 ' Active Min',
 'Idle Mean',
 ' Idle Std',
 ' Idle Max',
 ' Idle Min',
 ' Label']

In [19]:
monday.columns = monday.columns.str.strip()

In [20]:
monday.columns.tolist()

['Destination Port',
 'Flow Duration',
 'Total Fwd Packets',
 'Total Backward Packets',
 'Total Length of Fwd Packets',
 'Total Length of Bwd Packets',
 'Fwd Packet Length Max',
 'Fwd Packet Length Min',
 'Fwd Packet Length Mean',
 'Fwd Packet Length Std',
 'Bwd Packet Length Max',
 'Bwd Packet Length Min',
 'Bwd Packet Length Mean',
 'Bwd Packet Length Std',
 'Flow Bytes/s',
 'Flow Packets/s',
 'Flow IAT Mean',
 'Flow IAT Std',
 'Flow IAT Max',
 'Flow IAT Min',
 'Fwd IAT Total',
 'Fwd IAT Mean',
 'Fwd IAT Std',
 'Fwd IAT Max',
 'Fwd IAT Min',
 'Bwd IAT Total',
 'Bwd IAT Mean',
 'Bwd IAT Std',
 'Bwd IAT Max',
 'Bwd IAT Min',
 'Fwd PSH Flags',
 'Bwd PSH Flags',
 'Fwd URG Flags',
 'Bwd URG Flags',
 'Fwd Header Length',
 'Bwd Header Length',
 'Fwd Packets/s',
 'Bwd Packets/s',
 'Min Packet Length',
 'Max Packet Length',
 'Packet Length Mean',
 'Packet Length Std',
 'Packet Length Variance',
 'FIN Flag Count',
 'SYN Flag Count',
 'RST Flag Count',
 'PSH Flag Count',
 'ACK Flag Count',
 'URG Flag Count',
 'CWE Flag Count',
 'ECE Flag Count',
 'Down/Up Ratio',
 'Average Packet Size',
 'Avg Fwd Segment Size',
 'Avg Bwd Segment Size',
 'Fwd Header Length.1',
 'Fwd Avg Bytes/Bulk',
 'Fwd Avg Packets/Bulk',
 'Fwd Avg Bulk Rate',
 'Bwd Avg Bytes/Bulk',
 'Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate',
 'Subflow Fwd Packets',
 'Subflow Fwd Bytes',
 'Subflow Bwd Packets',
 'Subflow Bwd Bytes',
 'Init_Win_bytes_forward',
 'Init_Win_bytes_backward',
 'act_data_pkt_fwd',
 'min_seg_size_forward',
 'Active Mean',
 'Active Std',
 'Active Max',
 'Active Min',
 'Idle Mean',
 'Idle Std',
 'Idle Max',
 'Idle Min',
 'Label']

In [21]:
monday.info()

<class 'pandas.DataFrame'>
RangeIndex: 529918 entries, 0 to 529917
Data columns (total 79 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Destination Port             529918 non-null  int64
 1   Flow Duration                529918 non-null  int64
 2   Total Fwd Packets            529918 non-null  int64
 3   Total Backward Packets       529918 non-null  int64
 4   Total Length of Fwd Packets  529918 non-null  int64
 5   Total Length of Bwd Packets  529918 non-null  int64
 6   Fwd Packet Length Max        529918 non-null  int64
 7   Fwd Packet Length Min        529918 non-null  int64
 8   Fwd Packet Length Mean       529918 non-null  float64
 9   Fwd Packet Length Std        529918 non-null  float64
 10  Bwd Packet Length Max        529918 non-null  int64
 11  Bwd Packet Length Min        529918 non-null  int64
 12  Bwd Packet Length Mean       529918 non-null  float64
 13  Bwd Packet Length Std        529918 non-null  float64
 14  Flow Bytes/s                 529854 non-null  float64
 15  Flow Packets/s               529918 non-null  float64
 16  Flow IAT Mean                529918 non-null  float64
 17  Flow IAT Std                 529918 non-null  float64
 18  Flow IAT Max                 529918 non-null  int64
 19  Flow IAT Min                 529918 non-null  int64
 20  Fwd IAT Total                529918 non-null  int64
 21  Fwd IAT Mean                 529918 non-null  float64
 22  Fwd IAT Std                  529918 non-null  float64
 23  Fwd IAT Max                  529918 non-null  int64
 24  Fwd IAT Min                  529918 non-null  int64
 25  Bwd IAT Total                529918 non-null  int64
 26  Bwd IAT Mean                 529918 non-null  float64
 27  Bwd IAT Std                  529918 non-null  float64
 28  Bwd IAT Max                  529918 non-null  int64
 29  Bwd IAT Min                  529918 non-null  int64
 30  Fwd PSH Flags                529918 non-null  int64
 31  Bwd PSH Flags                529918 non-null  int64
 32  Fwd URG Flags                529918 non-null  int64
 33  Bwd URG Flags                529918 non-null  int64
 34  Fwd Header Length            529918 non-null  int64
 35  Bwd Header Length            529918 non-null  int64
 36  Fwd Packets/s                529918 non-null  float64
 37  Bwd Packets/s                529918 non-null  float64
 38  Min Packet Length            529918 non-null  int64
 39  Max Packet Length            529918 non-null  int64
 40  Packet Length Mean           529918 non-null  float64
 41  Packet Length Std            529918 non-null  float64
 42  Packet Length Variance       529918 non-null  float64
 43  FIN Flag Count               529918 non-null  int64
 44  SYN Flag Count               529918 non-null  int64
 45  RST Flag Count               529918 non-null  int64
 46  PSH Flag Count               529918 non-null  int64
 47  ACK Flag Count               529918 non-null  int64
 48  URG Flag Count               529918 non-null  int64
 49  CWE Flag Count               529918 non-null  int64
 50  ECE Flag Count               529918 non-null  int64
 51  Down/Up Ratio                529918 non-null  int64
 52  Average Packet Size          529918 non-null  float64
 53  Avg Fwd Segment Size         529918 non-null  float64
 54  Avg Bwd Segment Size         529918 non-null  float64
 55  Fwd Header Length.1          529918 non-null  int64
 56  Fwd Avg Bytes/Bulk           529918 non-null  int64
 57  Fwd Avg Packets/Bulk         529918 non-null  int64
 58  Fwd Avg Bulk Rate            529918 non-null  int64
 59  Bwd Avg Bytes/Bulk           529918 non-null  int64
 60  Bwd Avg Packets/Bulk         529918 non-null  int64
 61  Bwd Avg Bulk Rate            529918 non-null  int64
 62  Subflow Fwd Packets          529918 non-null  int64
 63  Subflow Fwd Bytes            529918 non-null  int64
 64  Subflow Bwd Packets          529918 non-null  int64
 65  Subflow Bwd Bytes            529918 non-null  int64
 66  Init_Win_bytes_forward       529918 non-null  int64
 67  Init_Win_bytes_backward      529918 non-null  int64
 68  act_data_pkt_fwd             529918 non-null  int64
 69  min_seg_size_forward         529918 non-null  int64
 70  Active Mean                  529918 non-null  float64
 71  Active Std                   529918 non-null  float64
 72  Active Max                   529918 non-null  int64
 73  Active Min                   529918 non-null  int64
 74  Idle Mean                    529918 non-null  float64
 75  Idle Std                     529918 non-null  float64
 76  Idle Max                     529918 non-null  int64
 77  Idle Min                     529918 non-null  int64
 78  Label                        529918 non-null  str
dtypes: float64(24), int64(54), str(1)
memory usage: 319.4 MB

In [22]:
monday.isnull().sum().sort_values(ascending=False)

Flow Bytes/s                   64
Flow Duration                   0
Destination Port                0
Total Backward Packets          0
Total Length of Fwd Packets     0
Total Length of Bwd Packets     0
Total Fwd Packets               0
Fwd Packet Length Max           0
Fwd Packet Length Min           0
Fwd Packet Length Std           0
Fwd Packet Length Mean          0
Bwd Packet Length Max           0
Bwd Packet Length Min           0
Bwd Packet Length Mean          0
Bwd Packet Length Std           0
Flow Packets/s                  0
Flow IAT Mean                   0
Flow IAT Std                    0
Flow IAT Max                    0
Flow IAT Min                    0
Fwd IAT Total                   0
Fwd IAT Mean                    0
Fwd IAT Std                     0
Fwd IAT Max                     0
Fwd IAT Min                     0
Bwd IAT Total                   0
Bwd IAT Mean                    0
Bwd IAT Std                     0
Bwd IAT Max                     0
Bwd IAT Min                     0
Fwd PSH Flags                   0
Bwd PSH Flags                   0
Fwd URG Flags                   0
Bwd URG Flags                   0
Fwd Header Length               0
Bwd Header Length               0
Fwd Packets/s                   0
Bwd Packets/s                   0
Min Packet Length               0
Max Packet Length               0
Packet Length Mean              0
Packet Length Std               0
Packet Length Variance          0
FIN Flag Count                  0
SYN Flag Count                  0
RST Flag Count                  0
PSH Flag Count                  0
ACK Flag Count                  0
URG Flag Count                  0
CWE Flag Count                  0
ECE Flag Count                  0
Down/Up Ratio                   0
Average Packet Size             0
Avg Fwd Segment Size            0
Avg Bwd Segment Size            0
Fwd Header Length.1             0
Fwd Avg Bytes/Bulk              0
Fwd Avg Packets/Bulk            0
Fwd Avg Bulk Rate               0
Bwd Avg Bytes/Bulk              0
Bwd Avg Packets/Bulk            0
Bwd Avg Bulk Rate               0
Subflow Fwd Packets             0
Subflow Fwd Bytes               0
Subflow Bwd Packets             0
Subflow Bwd Bytes               0
Init_Win_bytes_forward          0
Init_Win_bytes_backward         0
act_data_pkt_fwd                0
min_seg_size_forward            0
Active Mean                     0
Active Std                      0
Active Max                      0
Active Min                      0
Idle Mean                       0
Idle Std                        0
Idle Max                        0
Idle Min                        0
Label                           0
dtype: int64

In [23]:
monday[monday['Flow Bytes/s'].isnull()]

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
3986,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,33304,122,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
18905,80,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,256,340,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
21063,21,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,229,227,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
21794,49685,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,134,65535,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
25671,42440,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,227,229,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
29999,57960,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,365,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
42738,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,362,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
43266,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,351,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
48278,50772,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,365,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
49343,54268,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,370,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
59630,51540,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,362,32832,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
67846,41204,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,2081,253,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
70168,52042,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,5754,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
74870,56816,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,357,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
77420,54381,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,4662,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
84009,53889,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,480,33304,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
101095,46234,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,227,229,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
114551,80,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,274,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
139922,80,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,270,974,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
159081,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,362,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
170609,443,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,33290,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
171948,80,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,33304,285,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
172977,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,357,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
179934,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,357,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
182498,443,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,33285,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
193843,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,350,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
194688,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,357,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
198244,12803,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,33304,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
203375,63911,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,65535,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
212899,52968,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,406,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
226916,32786,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,340,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
227944,51762,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,370,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
240394,80,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,295,290,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
271348,21,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,229,227,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
272874,34490,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,118,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
282397,52569,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,118,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
308689,38708,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,135,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
312777,59702,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,60,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
320446,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,351,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
324988,41617,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,33304,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
335602,64718,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,408,65535,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
340585,54089,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,122,33304,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
343286,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,349,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
356546,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,33304,8192,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
363454,54960,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,6471,39096,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
373459,43716,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,292,392,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
379068,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,357,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
410123,60557,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,383,32832,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
410565,50381,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,349,32832,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
410936,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,357,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
415469,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,33304,128,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
416160,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,357,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
421971,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,65535,134,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
424564,51540,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,362,32832,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
427050,51206,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,370,332,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
437022,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,33304,122,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
441157,34527,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,340,240,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
448254,47038,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,3,229,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
451030,48579,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,229,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
472582,60890,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,5143,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
476509,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,32832,357,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
478399,443,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,33304,126,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
518787,42807,0,2,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,64,0,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0,64,0,0,0,0,0,0,2,0,0,0,5179,-1,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
524024,47037,0,1,1,0,0,0,0,0.0,0.0,0,0,0.0,0.0,NaN,inf,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,32,32,0.0,0.0,0,0,0.0,0.0,0.0,0,0,0,0,1,1,0,0,1,0.0,0.0,0.0,32,0,0,0,0,0,0,1,0,1,0,3,229,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [24]:
monday = monday.dropna(subset=['Flow Bytes/s'])

In [25]:
monday.isnull().sum().sum()

np.int64(0)

In [26]:
duplicates = monday.duplicated().sum()
print(duplicates)

26927

In [27]:
monday = monday.drop_duplicates()

In [28]:
print(monday.shape)

(502927, 79)

In [29]:
monday['Label'].value_counts()

Label
BENIGN    502927
Name: count, dtype: int64

In [30]:
monday['Label'].value_counts(normalize=True) * 100

Label
BENIGN    100.0
Name: proportion, dtype: float64

In [31]:
monday.dtypes

Destination Port                 int64
Flow Duration                    int64
Total Fwd Packets                int64
Total Backward Packets           int64
Total Length of Fwd Packets      int64
Total Length of Bwd Packets      int64
Fwd Packet Length Max            int64
Fwd Packet Length Min            int64
Fwd Packet Length Mean         float64
Fwd Packet Length Std          float64
Bwd Packet Length Max            int64
Bwd Packet Length Min            int64
Bwd Packet Length Mean         float64
Bwd Packet Length Std          float64
Flow Bytes/s                   float64
Flow Packets/s                 float64
Flow IAT Mean                  float64
Flow IAT Std                   float64
Flow IAT Max                     int64
Flow IAT Min                     int64
Fwd IAT Total                    int64
Fwd IAT Mean                   float64
Fwd IAT Std                    float64
Fwd IAT Max                      int64
Fwd IAT Min                      int64
Bwd IAT Total                    int64
Bwd IAT Mean                   float64
Bwd IAT Std                    float64
Bwd IAT Max                      int64
Bwd IAT Min                      int64
Fwd PSH Flags                    int64
Bwd PSH Flags                    int64
Fwd URG Flags                    int64
Bwd URG Flags                    int64
Fwd Header Length                int64
Bwd Header Length                int64
Fwd Packets/s                  float64
Bwd Packets/s                  float64
Min Packet Length                int64
Max Packet Length                int64
Packet Length Mean             float64
Packet Length Std              float64
Packet Length Variance         float64
FIN Flag Count                   int64
SYN Flag Count                   int64
RST Flag Count                   int64
PSH Flag Count                   int64
ACK Flag Count                   int64
URG Flag Count                   int64
CWE Flag Count                   int64
ECE Flag Count                   int64
Down/Up Ratio                    int64
Average Packet Size            float64
Avg Fwd Segment Size           float64
Avg Bwd Segment Size           float64
Fwd Header Length.1              int64
Fwd Avg Bytes/Bulk               int64
Fwd Avg Packets/Bulk             int64
Fwd Avg Bulk Rate                int64
Bwd Avg Bytes/Bulk               int64
Bwd Avg Packets/Bulk             int64
Bwd Avg Bulk Rate                int64
Subflow Fwd Packets              int64
Subflow Fwd Bytes                int64
Subflow Bwd Packets              int64
Subflow Bwd Bytes                int64
Init_Win_bytes_forward           int64
Init_Win_bytes_backward          int64
act_data_pkt_fwd                 int64
min_seg_size_forward             int64
Active Mean                    float64
Active Std                     float64
Active Max                       int64
Active Min                       int64
Idle Mean                      float64
Idle Std                       float64
Idle Max                         int64
Idle Min                         int64
Label                              str
dtype: object

In [33]:
tuesday = pd.read_csv(
    rf"{DATA_PATH}\Tuesday-WorkingHours.pcap_ISCX.csv"
)

In [34]:
tuesday.columns = tuesday.columns.str.strip()

In [35]:
tuesday.shape

(445909, 79)

In [36]:
tuesday['Label'].value_counts()

Label
BENIGN         432074
FTP-Patator      7938
SSH-Patator      5897
Name: count, dtype: int64

In [37]:
tuesday.isnull().sum().sort_values(ascending=False)

Flow Bytes/s                   201
Flow Duration                    0
Destination Port                 0
Total Backward Packets           0
Total Length of Fwd Packets      0
Total Length of Bwd Packets      0
Total Fwd Packets                0
Fwd Packet Length Max            0
Fwd Packet Length Min            0
Fwd Packet Length Std            0
Fwd Packet Length Mean           0
Bwd Packet Length Max            0
Bwd Packet Length Min            0
Bwd Packet Length Mean           0
Bwd Packet Length Std            0
Flow Packets/s                   0
Flow IAT Mean                    0
Flow IAT Std                     0
Flow IAT Max                     0
Flow IAT Min                     0
Fwd IAT Total                    0
Fwd IAT Mean                     0
Fwd IAT Std                      0
Fwd IAT Max                      0
Fwd IAT Min                      0
Bwd IAT Total                    0
Bwd IAT Mean                     0
Bwd IAT Std                      0
Bwd IAT Max                      0
Bwd IAT Min                      0
Fwd PSH Flags                    0
Bwd PSH Flags                    0
Fwd URG Flags                    0
Bwd URG Flags                    0
Fwd Header Length                0
Bwd Header Length                0
Fwd Packets/s                    0
Bwd Packets/s                    0
Min Packet Length                0
Max Packet Length                0
Packet Length Mean               0
Packet Length Std                0
Packet Length Variance           0
FIN Flag Count                   0
SYN Flag Count                   0
RST Flag Count                   0
PSH Flag Count                   0
ACK Flag Count                   0
URG Flag Count                   0
CWE Flag Count                   0
ECE Flag Count                   0
Down/Up Ratio                    0
Average Packet Size              0
Avg Fwd Segment Size             0
Avg Bwd Segment Size             0
Fwd Header Length.1              0
Fwd Avg Bytes/Bulk               0
Fwd Avg Packets/Bulk             0
Fwd Avg Bulk Rate                0
Bwd Avg Bytes/Bulk               0
Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                0
Subflow Fwd Packets              0
Subflow Fwd Bytes                0
Subflow Bwd Packets              0
Subflow Bwd Bytes                0
Init_Win_bytes_forward           0
Init_Win_bytes_backward          0
act_data_pkt_fwd                 0
min_seg_size_forward             0
Active Mean                      0
Active Std                       0
Active Max                       0
Active Min                       0
Idle Mean                        0
Idle Std                         0
Idle Max                         0
Idle Min                         0
Label                            0
dtype: int64

In [38]:
tuesday.duplicated().sum()

np.int64(24065)

In [39]:
np.isinf(
    tuesday.select_dtypes(include=np.number)
).sum()

Destination Port                 0
Flow Duration                    0
Total Fwd Packets                0
Total Backward Packets           0
Total Length of Fwd Packets      0
Total Length of Bwd Packets      0
Fwd Packet Length Max            0
Fwd Packet Length Min            0
Fwd Packet Length Mean           0
Fwd Packet Length Std            0
Bwd Packet Length Max            0
Bwd Packet Length Min            0
Bwd Packet Length Mean           0
Bwd Packet Length Std            0
Flow Bytes/s                    63
Flow Packets/s                 264
Flow IAT Mean                    0
Flow IAT Std                     0
Flow IAT Max                     0
Flow IAT Min                     0
Fwd IAT Total                    0
Fwd IAT Mean                     0
Fwd IAT Std                      0
Fwd IAT Max                      0
Fwd IAT Min                      0
Bwd IAT Total                    0
Bwd IAT Mean                     0
Bwd IAT Std                      0
Bwd IAT Max                      0
Bwd IAT Min                      0
Fwd PSH Flags                    0
Bwd PSH Flags                    0
Fwd URG Flags                    0
Bwd URG Flags                    0
Fwd Header Length                0
Bwd Header Length                0
Fwd Packets/s                    0
Bwd Packets/s                    0
Min Packet Length                0
Max Packet Length                0
Packet Length Mean               0
Packet Length Std                0
Packet Length Variance           0
FIN Flag Count                   0
SYN Flag Count                   0
RST Flag Count                   0
PSH Flag Count                   0
ACK Flag Count                   0
URG Flag Count                   0
CWE Flag Count                   0
ECE Flag Count                   0
Down/Up Ratio                    0
Average Packet Size              0
Avg Fwd Segment Size             0
Avg Bwd Segment Size             0
Fwd Header Length.1              0
Fwd Avg Bytes/Bulk               0
Fwd Avg Packets/Bulk             0
Fwd Avg Bulk Rate                0
Bwd Avg Bytes/Bulk               0
Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                0
Subflow Fwd Packets              0
Subflow Fwd Bytes                0
Subflow Bwd Packets              0
Subflow Bwd Bytes                0
Init_Win_bytes_forward           0
Init_Win_bytes_backward          0
act_data_pkt_fwd                 0
min_seg_size_forward             0
Active Mean                      0
Active Std                       0
Active Max                       0
Active Min                       0
Idle Mean                        0
Idle Std                         0
Idle Max                         0
Idle Min                         0
dtype: int64

In [40]:
tuesday.replace([np.inf, -np.inf], np.nan, inplace=True)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,88,640,7,4,440,358,220,0,62.857143,107.349008,179,0,89.5,103.345698,1246875.000,17187.500000,64.000000,135.557286,445,1,640,106.666667,194.325157,497,1,538,179.333333,303.686242,530,4,0,0,0,0,164,104,10937.500000,6250.000000,0,220,66.500000,99.001837,9801.363636,0,0,0,1,0,0,0,0,0,72.545455,62.857143,89.5,164,0,0,0,0,0,0,7,440,4,358,8192,2053,2,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,88,900,9,4,600,2944,300,0,66.666667,132.287566,1472,0,736.0,849.859596,3937777.778,14444.444440,75.000000,192.795228,684,1,900,112.500000,252.411229,734,1,766,255.333333,435.323252,758,3,0,0,0,0,204,104,10000.000000,4444.444444,0,1472,253.142857,527.434262,278186.901100,0,0,0,1,0,0,0,0,0,272.615385,66.666667,736.0,204,0,0,0,0,0,0,9,600,4,2944,8192,2053,2,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,88,1205,7,4,2776,2830,1388,0,396.571429,677.274651,1415,0,707.5,816.950631,4652282.158,9128.630705,120.500000,236.433336,777,1,1205,200.833333,397.058392,1008,1,927,309.000000,491.647231,876,1,0,0,0,0,164,104,5809.128631,3319.502075,0,1415,467.166667,690.098917,476236.515200,0,0,0,1,0,0,0,0,0,509.636364,396.571429,707.5,164,0,0,0,0,0,0,7,2776,4,2830,8192,2053,2,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,88,511,7,4,452,370,226,0,64.571429,110.276708,185,0,92.5,106.809800,1608610.568,21526.418790,51.100000,90.767652,299,1,511,85.166667,131.900594,349,1,462,154.000000,224.719826,412,1,0,0,0,0,164,104,13698.630140,7827.788650,0,226,68.500000,101.933579,10390.454550,0,0,0,1,0,0,0,0,0,74.727273,64.571429,92.5,164,0,0,0,0,0,0,7,452,4,370,8192,2053,2,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,88,773,9,4,612,2944,306,0,68.000000,134.933317,1472,0,736.0,849.859596,4600258.732,16817.593790,64.416667,148.698266,531,1,773,96.625000,196.665733,580,1,675,225.000000,348.901132,627,1,0,0,0,0,204,104,11642.949550,5174.644243,0,1472,254.000000,527.520762,278278.153800,0,0,0,1,0,0,0,0,0,273.538461,68.000000,736.0,204,0,0,0,0,0,0,9,612,4,2944,8192,2053,2,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445904,53,155,2,2,88,120,44,44,44.000000,0.000000,60,60,60.0,0.000000,1341935.484,25806.451610,51.666667,83.428612,148,3,3,3.000000,0.000000,3,3,4,4.000000,0.000000,4,4,0,0,0,0,64,64,12903.225810,12903.225810,44,60,50.400000,8.763561,76.800000,0,0,0,0,0,0,0,0,1,63.000000,44.000000,60.0,64,0,0,0,0,0,0,2,88,2,120,-1,-1,1,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
445905,59317,110,1,1,0,0,0,0,0.000000,0.000000,0,0,0.0,0.000000,0.000,18181.818180,110.000000,0.000000,110,110,0,0.000000,0.000000,0,0,0,0.000000,0.000000,0,0,0,0,0,0,20,20,9090.909091,9090.909091,0,0,0.000000,0.000000,0.000000,0,0,0,0,1,1,0,0,1,0.000000,0.000000,0.0,20,0,0,0,0,0,0,1,0,1,0,64,256,0,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
445906,53,166,2,2,88,188,44,44,44.000000,0.000000,94,94,94.0,0.000000,1662650.602,24096.385540,55.333333,90.643992,160,3,3,3.000000,0.000000,3,3,3,3.000000,0.000000,3,3,0,0,0,0,64,64,12048.192770,12048.192770,44,94,64.000000,27.386128,750.000000,0,0,0,0,0,0,0,0,1,80.000000,44.000000,94.0,64,0,0,0,0,0,0,2,88,2,188,-1,-1,1,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
445907,54726,81,1,1,0,0,0,0,0.000000,0.000000,0,0,0.0,0.000000,0.000,24691.358020,81.000000,0.000000,81,81,0,0.000000,0.000000,0,0,0,0.000000,0.000000,0,0,0,0,0,0,32,32,12345.679010,12345.679010,0,0,0.000000,0.000000,0.000000,0,0,0,0,1,0,0,0,1,0.000000,0.000000,0.0,32,0,0,0,0,0,0,1,0,1,0,122,33304,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
445908,53,202,2,2,102,158,51,51,51.000000,0.000000,79,79,79.0,0.000000,1287128.713,19801.980200,67.333333,77.151366,152,1,1,1.000000,0.000000,1,1,49,49.000000,0.000000,49,49,0,0,0,0,40,40,9900.990099,9900.990099,51,79,62.200000,15.336232,235.200000,0,0,0,0,0,0,0,0,1,77.750000,51.000000,79.0,40,0,0,0,0,0,0,2,102,2,158,-1,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [41]:
np.isinf(
    tuesday.select_dtypes(include=np.number)
).sum().sum()

np.int64(0)

In [42]:
tuesday.dropna(inplace=True)

In [43]:
tuesday.drop_duplicates(inplace=True)

In [44]:
tuesday.shape

(421626, 79)

In [45]:
tuesday.isnull().sum().sum()

np.int64(0)

In [46]:
tuesday.duplicated().sum()

np.int64(0)

In [47]:
wednesday = pd.read_csv(
    rf"{DATA_PATH}\Wednesday-workingHours.pcap_ISCX.csv"
)

In [48]:
wednesday.columns = wednesday.columns.str.strip()

In [49]:
wednesday.shape

(692703, 79)

In [50]:
wednesday['Label'].value_counts()

Label
BENIGN              440031
DoS Hulk            231073
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Heartbleed              11
Name: count, dtype: int64

In [51]:
wednesday.isnull().sum().sort_values(ascending=False)

Flow Bytes/s                   1008
Flow Duration                     0
Destination Port                  0
Total Backward Packets            0
Total Length of Fwd Packets       0
Total Length of Bwd Packets       0
Total Fwd Packets                 0
Fwd Packet Length Max             0
Fwd Packet Length Min             0
Fwd Packet Length Std             0
Fwd Packet Length Mean            0
Bwd Packet Length Max             0
Bwd Packet Length Min             0
Bwd Packet Length Mean            0
Bwd Packet Length Std             0
Flow Packets/s                    0
Flow IAT Mean                     0
Flow IAT Std                      0
Flow IAT Max                      0
Flow IAT Min                      0
Fwd IAT Total                     0
Fwd IAT Mean                      0
Fwd IAT Std                       0
Fwd IAT Max                       0
Fwd IAT Min                       0
Bwd IAT Total                     0
Bwd IAT Mean                      0
Bwd IAT Std                       0
Bwd IAT Max                       0
Bwd IAT Min                       0
Fwd PSH Flags                     0
Bwd PSH Flags                     0
Fwd URG Flags                     0
Bwd URG Flags                     0
Fwd Header Length                 0
Bwd Header Length                 0
Fwd Packets/s                     0
Bwd Packets/s                     0
Min Packet Length                 0
Max Packet Length                 0
Packet Length Mean                0
Packet Length Std                 0
Packet Length Variance            0
FIN Flag Count                    0
SYN Flag Count                    0
RST Flag Count                    0
PSH Flag Count                    0
ACK Flag Count                    0
URG Flag Count                    0
CWE Flag Count                    0
ECE Flag Count                    0
Down/Up Ratio                     0
Average Packet Size               0
Avg Fwd Segment Size              0
Avg Bwd Segment Size              0
Fwd Header Length.1               0
Fwd Avg Bytes/Bulk                0
Fwd Avg Packets/Bulk              0
Fwd Avg Bulk Rate                 0
Bwd Avg Bytes/Bulk                0
Bwd Avg Packets/Bulk              0
Bwd Avg Bulk Rate                 0
Subflow Fwd Packets               0
Subflow Fwd Bytes                 0
Subflow Bwd Packets               0
Subflow Bwd Bytes                 0
Init_Win_bytes_forward            0
Init_Win_bytes_backward           0
act_data_pkt_fwd                  0
min_seg_size_forward              0
Active Mean                       0
Active Std                        0
Active Max                        0
Active Min                        0
Idle Mean                         0
Idle Std                          0
Idle Max                          0
Idle Min                          0
Label                             0
dtype: int64

In [52]:
wednesday.duplicated().sum()

np.int64(81909)

In [53]:
np.isinf(
    wednesday.select_dtypes(include=np.number)
).sum()

Destination Port                  0
Flow Duration                     0
Total Fwd Packets                 0
Total Backward Packets            0
Total Length of Fwd Packets       0
Total Length of Bwd Packets       0
Fwd Packet Length Max             0
Fwd Packet Length Min             0
Fwd Packet Length Mean            0
Fwd Packet Length Std             0
Bwd Packet Length Max             0
Bwd Packet Length Min             0
Bwd Packet Length Mean            0
Bwd Packet Length Std             0
Flow Bytes/s                    289
Flow Packets/s                 1297
Flow IAT Mean                     0
Flow IAT Std                      0
Flow IAT Max                      0
Flow IAT Min                      0
Fwd IAT Total                     0
Fwd IAT Mean                      0
Fwd IAT Std                       0
Fwd IAT Max                       0
Fwd IAT Min                       0
Bwd IAT Total                     0
Bwd IAT Mean                      0
Bwd IAT Std                       0
Bwd IAT Max                       0
Bwd IAT Min                       0
Fwd PSH Flags                     0
Bwd PSH Flags                     0
Fwd URG Flags                     0
Bwd URG Flags                     0
Fwd Header Length                 0
Bwd Header Length                 0
Fwd Packets/s                     0
Bwd Packets/s                     0
Min Packet Length                 0
Max Packet Length                 0
Packet Length Mean                0
Packet Length Std                 0
Packet Length Variance            0
FIN Flag Count                    0
SYN Flag Count                    0
RST Flag Count                    0
PSH Flag Count                    0
ACK Flag Count                    0
URG Flag Count                    0
CWE Flag Count                    0
ECE Flag Count                    0
Down/Up Ratio                     0
Average Packet Size               0
Avg Fwd Segment Size              0
Avg Bwd Segment Size              0
Fwd Header Length.1               0
Fwd Avg Bytes/Bulk                0
Fwd Avg Packets/Bulk              0
Fwd Avg Bulk Rate                 0
Bwd Avg Bytes/Bulk                0
Bwd Avg Packets/Bulk              0
Bwd Avg Bulk Rate                 0
Subflow Fwd Packets               0
Subflow Fwd Bytes                 0
Subflow Bwd Packets               0
Subflow Bwd Bytes                 0
Init_Win_bytes_forward            0
Init_Win_bytes_backward           0
act_data_pkt_fwd                  0
min_seg_size_forward              0
Active Mean                       0
Active Std                        0
Active Max                        0
Active Min                        0
Idle Mean                         0
Idle Std                          0
Idle Max                          0
Idle Min                          0
dtype: int64

In [54]:
wednesday.replace([np.inf, -np.inf], np.nan, inplace=True)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,38308,1,1,6,6,6,6,6.000000,0.000000,6,6,6.000000,0.000000,3.132505e+02,52.208416,38308.000000,0.000000,38308,38308,0,0.000000,0.000000,0,0,0,0.000000,0.000000,0,0,0,0,0,0,20,20,26.104208,26.104208,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,1,0,0,1,9.000000,6.000000,6.000000,20,0,0,0,0,0,0,1,6,1,6,255,946,0,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,389,479,11,5,172,326,79,0,15.636364,31.449238,163,0,65.200000,89.278777,1.039666e+06,33402.922760,31.933333,25.510409,73,0,479,47.900000,38.942836,109,1,401,100.250000,101.736178,237,3,0,0,0,0,368,176,22964.509390,10438.413360,0,163,29.294118,56.529599,3195.595588,0,0,0,1,0,0,0,0,0,31.125000,15.636364,65.200000,368,0,0,0,0,0,0,11,172,5,326,29200,260,4,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,88,1095,10,6,3150,3150,1575,0,315.000000,632.561635,1575,0,525.000000,813.326503,5.753425e+06,14611.872150,73.000000,204.960972,810,1,1095,121.666667,298.746130,915,1,995,199.000000,345.535092,810,3,0,0,0,0,336,208,9132.420091,5479.452055,0,1575,370.588235,671.751541,451250.132400,0,0,0,1,0,0,0,0,0,393.750000,315.000000,525.000000,336,0,0,0,0,0,0,10,3150,6,3150,29200,2081,3,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,389,15206,17,12,3452,6660,1313,0,203.058823,425.778474,3069,0,555.000000,977.480342,6.650007e+05,1907.141918,543.071429,2519.931377,13391,0,15206,950.375000,3322.417812,13391,2,15112,1373.818182,4176.449588,13961,3,0,0,0,0,560,388,1117.979745,789.162173,0,3069,337.066667,704.654082,496537.374700,0,0,0,1,0,0,0,0,0,348.689655,203.058823,555.000000,560,0,0,0,0,0,0,17,3452,12,6660,29200,0,10,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,88,1092,9,6,3150,3152,1575,0,350.000000,694.509719,1576,0,525.333333,813.842901,5.771062e+06,13736.263740,78.000000,207.000929,794,1,1092,136.500000,313.850738,910,1,1015,203.000000,333.240154,794,3,0,0,0,0,304,208,8241.758242,5494.505495,0,1576,393.875000,704.585067,496440.116700,0,0,0,1,0,0,0,0,0,420.133333,350.000000,525.333333,304,0,0,0,0,0,0,9,3150,6,3152,29200,2081,2,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692698,53,32215,4,2,112,152,28,28,28.000000,0.000000,76,76,76.000000,0.000000,8.194940e+03,186.248642,6443.000000,13617.579480,30780,3,30832,10277.333330,17755.843810,30780,4,3,3.000000,0.000000,3,3,0,0,0,0,80,64,124.165761,62.082881,28,76,41.714286,23.421602,548.571429,0,0,0,0,0,0,0,0,0,48.666667,28.000000,76.000000,80,0,0,0,0,0,0,4,112,2,152,-1,-1,3,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
692699,53,324,2,2,84,362,42,42,42.000000,0.000000,181,181,181.000000,0.000000,1.376543e+06,12345.679010,108.000000,183.597386,320,2,2,2.000000,0.000000,2,2,2,2.000000,0.000000,2,2,0,0,0,0,40,40,6172.839506,6172.839506,42,181,97.600000,76.133435,5796.300000,0,0,0,0,0,0,0,0,1,122.000000,42.000000,181.000000,40,0,0,0,0,0,0,2,84,2,362,-1,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
692700,58030,82,2,1,31,6,31,0,15.500000,21.920310,6,6,6.000000,0.000000,4.512195e+05,36585.365850,41.000000,52.325902,78,4,4,4.000000,0.000000,4,4,0,0.000000,0.000000,0,0,1,0,0,0,64,20,24390.243900,12195.121950,0,31,17.000000,16.350331,267.333333,0,1,0,0,1,0,0,0,0,22.666667,15.500000,6.000000,64,0,0,0,0,0,0,2,31,1,6,1006,0,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
692701,53,1048635,6,2,192,256,32,32,32.000000,0.000000,128,128,128.000000,0.000000,4.272221e+02,7.628965,149805.000000,375521.040500,1000947,1,1033613,206722.600000,444210.068600,1000947,1,3,3.000000,0.000000,3,3,0,0,0,0,120,40,5.721724,1.907241,32,128,53.333333,42.332021,1792.000000,0,0,0,0,0,0,0,0,0,60.000000,32.000000,128.000000,120,0,0,0,0,0,0,6,192,2,256,-1,-1,5,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
692702,53,94939,4,2,188,226,47,47,47.000000,0.000000,113,113,113.000000,0.000000,4.360695e+03,63.198475,18987.800000,31664.102560,73049,1,73051,24350.333330,42174.282460,73049,1,48,48.000000,0.000000,48,48,0,0,0,0,104,64,42.132317,21.066158,47,113,65.857143,32.204702,1037.142857,0,0,0,0,0,0,0,0,0,76.833333,47.000000,113.000000,104,0,0,0,0,0,0,4,188,2,226,-1,-1,3,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [55]:
wednesday.dropna(inplace=True)

In [56]:
wednesday.drop_duplicates(inplace=True)

In [57]:
wednesday.shape

(610492, 79)

In [58]:
wednesday.isnull().sum().sum()

np.int64(0)

In [59]:
wednesday.duplicated().sum()

np.int64(0)

In [60]:
thursday_morning = pd.read_csv(
    rf"{DATA_PATH}\Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv"
)

thursday_afternoon = pd.read_csv(
    rf"{DATA_PATH}\Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv"
)

In [61]:
thursday_morning.columns = thursday_morning.columns.str.strip()

thursday_afternoon.columns = thursday_afternoon.columns.str.strip()

In [62]:
print(thursday_morning.shape)
print(thursday_afternoon.shape)

(170366, 79)
(288602, 79)

In [63]:
print(thursday_morning['Label'].value_counts())

Label
BENIGN                        168186
Web Attack � Brute Force        1507
Web Attack � XSS                 652
Web Attack � Sql Injection        21
Name: count, dtype: int64

In [64]:
print(thursday_afternoon['Label'].value_counts())

Label
BENIGN          288566
Infiltration        36
Name: count, dtype: int64

In [65]:
thursday_morning.columns.equals(
    thursday_afternoon.columns
)

True

In [66]:
thursday_morning.isnull().sum().sort_values(ascending=False)

Flow Bytes/s                   20
Flow Duration                   0
Destination Port                0
Total Backward Packets          0
Total Length of Fwd Packets     0
Total Length of Bwd Packets     0
Total Fwd Packets               0
Fwd Packet Length Max           0
Fwd Packet Length Min           0
Fwd Packet Length Std           0
Fwd Packet Length Mean          0
Bwd Packet Length Max           0
Bwd Packet Length Min           0
Bwd Packet Length Mean          0
Bwd Packet Length Std           0
Flow Packets/s                  0
Flow IAT Mean                   0
Flow IAT Std                    0
Flow IAT Max                    0
Flow IAT Min                    0
Fwd IAT Total                   0
Fwd IAT Mean                    0
Fwd IAT Std                     0
Fwd IAT Max                     0
Fwd IAT Min                     0
Bwd IAT Total                   0
Bwd IAT Mean                    0
Bwd IAT Std                     0
Bwd IAT Max                     0
Bwd IAT Min                     0
Fwd PSH Flags                   0
Bwd PSH Flags                   0
Fwd URG Flags                   0
Bwd URG Flags                   0
Fwd Header Length               0
Bwd Header Length               0
Fwd Packets/s                   0
Bwd Packets/s                   0
Min Packet Length               0
Max Packet Length               0
Packet Length Mean              0
Packet Length Std               0
Packet Length Variance          0
FIN Flag Count                  0
SYN Flag Count                  0
RST Flag Count                  0
PSH Flag Count                  0
ACK Flag Count                  0
URG Flag Count                  0
CWE Flag Count                  0
ECE Flag Count                  0
Down/Up Ratio                   0
Average Packet Size             0
Avg Fwd Segment Size            0
Avg Bwd Segment Size            0
Fwd Header Length.1             0
Fwd Avg Bytes/Bulk              0
Fwd Avg Packets/Bulk            0
Fwd Avg Bulk Rate               0
Bwd Avg Bytes/Bulk              0
Bwd Avg Packets/Bulk            0
Bwd Avg Bulk Rate               0
Subflow Fwd Packets             0
Subflow Fwd Bytes               0
Subflow Bwd Packets             0
Subflow Bwd Bytes               0
Init_Win_bytes_forward          0
Init_Win_bytes_backward         0
act_data_pkt_fwd                0
min_seg_size_forward            0
Active Mean                     0
Active Std                      0
Active Max                      0
Active Min                      0
Idle Mean                       0
Idle Std                        0
Idle Max                        0
Idle Min                        0
Label                           0
dtype: int64

In [67]:
thursday_afternoon.isnull().sum().sort_values(ascending=False)

Flow Bytes/s                   18
Flow Duration                   0
Destination Port                0
Total Backward Packets          0
Total Length of Fwd Packets     0
Total Length of Bwd Packets     0
Total Fwd Packets               0
Fwd Packet Length Max           0
Fwd Packet Length Min           0
Fwd Packet Length Std           0
Fwd Packet Length Mean          0
Bwd Packet Length Max           0
Bwd Packet Length Min           0
Bwd Packet Length Mean          0
Bwd Packet Length Std           0
Flow Packets/s                  0
Flow IAT Mean                   0
Flow IAT Std                    0
Flow IAT Max                    0
Flow IAT Min                    0
Fwd IAT Total                   0
Fwd IAT Mean                    0
Fwd IAT Std                     0
Fwd IAT Max                     0
Fwd IAT Min                     0
Bwd IAT Total                   0
Bwd IAT Mean                    0
Bwd IAT Std                     0
Bwd IAT Max                     0
Bwd IAT Min                     0
Fwd PSH Flags                   0
Bwd PSH Flags                   0
Fwd URG Flags                   0
Bwd URG Flags                   0
Fwd Header Length               0
Bwd Header Length               0
Fwd Packets/s                   0
Bwd Packets/s                   0
Min Packet Length               0
Max Packet Length               0
Packet Length Mean              0
Packet Length Std               0
Packet Length Variance          0
FIN Flag Count                  0
SYN Flag Count                  0
RST Flag Count                  0
PSH Flag Count                  0
ACK Flag Count                  0
URG Flag Count                  0
CWE Flag Count                  0
ECE Flag Count                  0
Down/Up Ratio                   0
Average Packet Size             0
Avg Fwd Segment Size            0
Avg Bwd Segment Size            0
Fwd Header Length.1             0
Fwd Avg Bytes/Bulk              0
Fwd Avg Packets/Bulk            0
Fwd Avg Bulk Rate               0
Bwd Avg Bytes/Bulk              0
Bwd Avg Packets/Bulk            0
Bwd Avg Bulk Rate               0
Subflow Fwd Packets             0
Subflow Fwd Bytes               0
Subflow Bwd Packets             0
Subflow Bwd Bytes               0
Init_Win_bytes_forward          0
Init_Win_bytes_backward         0
act_data_pkt_fwd                0
min_seg_size_forward            0
Active Mean                     0
Active Std                      0
Active Max                      0
Active Min                      0
Idle Mean                       0
Idle Std                        0
Idle Max                        0
Idle Min                        0
Label                           0
dtype: int64

In [68]:
thursday_morning.duplicated().sum()

np.int64(6066)

In [69]:
thursday_afternoon.duplicated().sum()

np.int64(35630)

In [70]:
np.isinf(
    thursday_morning.select_dtypes(include=np.number)
).sum()

Destination Port                 0
Flow Duration                    0
Total Fwd Packets                0
Total Backward Packets           0
Total Length of Fwd Packets      0
Total Length of Bwd Packets      0
Fwd Packet Length Max            0
Fwd Packet Length Min            0
Fwd Packet Length Mean           0
Fwd Packet Length Std            0
Bwd Packet Length Max            0
Bwd Packet Length Min            0
Bwd Packet Length Mean           0
Bwd Packet Length Std            0
Flow Bytes/s                   115
Flow Packets/s                 135
Flow IAT Mean                    0
Flow IAT Std                     0
Flow IAT Max                     0
Flow IAT Min                     0
Fwd IAT Total                    0
Fwd IAT Mean                     0
Fwd IAT Std                      0
Fwd IAT Max                      0
Fwd IAT Min                      0
Bwd IAT Total                    0
Bwd IAT Mean                     0
Bwd IAT Std                      0
Bwd IAT Max                      0
Bwd IAT Min                      0
Fwd PSH Flags                    0
Bwd PSH Flags                    0
Fwd URG Flags                    0
Bwd URG Flags                    0
Fwd Header Length                0
Bwd Header Length                0
Fwd Packets/s                    0
Bwd Packets/s                    0
Min Packet Length                0
Max Packet Length                0
Packet Length Mean               0
Packet Length Std                0
Packet Length Variance           0
FIN Flag Count                   0
SYN Flag Count                   0
RST Flag Count                   0
PSH Flag Count                   0
ACK Flag Count                   0
URG Flag Count                   0
CWE Flag Count                   0
ECE Flag Count                   0
Down/Up Ratio                    0
Average Packet Size              0
Avg Fwd Segment Size             0
Avg Bwd Segment Size             0
Fwd Header Length.1              0
Fwd Avg Bytes/Bulk               0
Fwd Avg Packets/Bulk             0
Fwd Avg Bulk Rate                0
Bwd Avg Bytes/Bulk               0
Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                0
Subflow Fwd Packets              0
Subflow Fwd Bytes                0
Subflow Bwd Packets              0
Subflow Bwd Bytes                0
Init_Win_bytes_forward           0
Init_Win_bytes_backward          0
act_data_pkt_fwd                 0
min_seg_size_forward             0
Active Mean                      0
Active Std                       0
Active Max                       0
Active Min                       0
Idle Mean                        0
Idle Std                         0
Idle Max                         0
Idle Min                         0
dtype: int64

In [71]:
np.isinf(
    thursday_afternoon.select_dtypes(include=np.number)
).sum()

Destination Port                 0
Flow Duration                    0
Total Fwd Packets                0
Total Backward Packets           0
Total Length of Fwd Packets      0
Total Length of Bwd Packets      0
Fwd Packet Length Max            0
Fwd Packet Length Min            0
Fwd Packet Length Mean           0
Fwd Packet Length Std            0
Bwd Packet Length Max            0
Bwd Packet Length Min            0
Bwd Packet Length Mean           0
Bwd Packet Length Std            0
Flow Bytes/s                   189
Flow Packets/s                 207
Flow IAT Mean                    0
Flow IAT Std                     0
Flow IAT Max                     0
Flow IAT Min                     0
Fwd IAT Total                    0
Fwd IAT Mean                     0
Fwd IAT Std                      0
Fwd IAT Max                      0
Fwd IAT Min                      0
Bwd IAT Total                    0
Bwd IAT Mean                     0
Bwd IAT Std                      0
Bwd IAT Max                      0
Bwd IAT Min                      0
Fwd PSH Flags                    0
Bwd PSH Flags                    0
Fwd URG Flags                    0
Bwd URG Flags                    0
Fwd Header Length                0
Bwd Header Length                0
Fwd Packets/s                    0
Bwd Packets/s                    0
Min Packet Length                0
Max Packet Length                0
Packet Length Mean               0
Packet Length Std                0
Packet Length Variance           0
FIN Flag Count                   0
SYN Flag Count                   0
RST Flag Count                   0
PSH Flag Count                   0
ACK Flag Count                   0
URG Flag Count                   0
CWE Flag Count                   0
ECE Flag Count                   0
Down/Up Ratio                    0
Average Packet Size              0
Avg Fwd Segment Size             0
Avg Bwd Segment Size             0
Fwd Header Length.1              0
Fwd Avg Bytes/Bulk               0
Fwd Avg Packets/Bulk             0
Fwd Avg Bulk Rate                0
Bwd Avg Bytes/Bulk               0
Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                0
Subflow Fwd Packets              0
Subflow Fwd Bytes                0
Subflow Bwd Packets              0
Subflow Bwd Bytes                0
Init_Win_bytes_forward           0
Init_Win_bytes_backward          0
act_data_pkt_fwd                 0
min_seg_size_forward             0
Active Mean                      0
Active Std                       0
Active Max                       0
Active Min                       0
Idle Mean                        0
Idle Std                         0
Idle Max                         0
Idle Min                         0
dtype: int64

In [72]:
thursday_morning.replace(
    [np.inf, -np.inf],
    np.nan,
    inplace=True
)

thursday_morning.dropna(inplace=True)

thursday_morning.drop_duplicates(inplace=True)

In [73]:
thursday_afternoon.replace(
    [np.inf, -np.inf],
    np.nan,
    inplace=True
)

thursday_afternoon.dropna(inplace=True)

thursday_afternoon.drop_duplicates(inplace=True)

In [74]:
print(thursday_morning.shape)

print(thursday_morning.isnull().sum().sum())

print(thursday_morning.duplicated().sum())

(164179, 79)
0
0

In [75]:
print(thursday_afternoon.shape)

print(thursday_afternoon.isnull().sum().sum())

print(thursday_afternoon.duplicated().sum())

(252790, 79)
0
0

In [76]:
thursday = pd.concat(
    [thursday_morning, thursday_afternoon],
    ignore_index=True
)

In [77]:
thursday.shape

(416969, 79)

In [78]:
thursday['Label'].value_counts()

Label
BENIGN                        414790
Web Attack � Brute Force        1470
Web Attack � XSS                 652
Infiltration                      36
Web Attack � Sql Injection        21
Name: count, dtype: int64

In [79]:
friday_morning = pd.read_csv(
    rf"{DATA_PATH}\Friday-WorkingHours-Morning.pcap_ISCX.csv"
)

friday_portscan = pd.read_csv(
    rf"{DATA_PATH}\Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv"
)

friday_ddos = pd.read_csv(
    rf"{DATA_PATH}\Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"
)

In [80]:
friday_morning.columns = friday_morning.columns.str.strip()

friday_portscan.columns = friday_portscan.columns.str.strip()

friday_ddos.columns = friday_ddos.columns.str.strip()

In [81]:
print(friday_morning.shape)

print(friday_portscan.shape)

print(friday_ddos.shape)

(191033, 79)
(286467, 79)
(225745, 79)

In [82]:
print(friday_morning['Label'].value_counts())
print(friday_portscan['Label'].value_counts())
print(friday_ddos['Label'].value_counts())

Label
BENIGN    189067
Bot         1966
Name: count, dtype: int64
Label
PortScan    158930
BENIGN      127537
Name: count, dtype: int64
Label
DDoS      128027
BENIGN     97718
Name: count, dtype: int64

In [83]:
friday_morning.isnull().sum().sort_values(ascending=False)

Flow Bytes/s                   28
Flow Duration                   0
Destination Port                0
Total Backward Packets          0
Total Length of Fwd Packets     0
Total Length of Bwd Packets     0
Total Fwd Packets               0
Fwd Packet Length Max           0
Fwd Packet Length Min           0
Fwd Packet Length Std           0
Fwd Packet Length Mean          0
Bwd Packet Length Max           0
Bwd Packet Length Min           0
Bwd Packet Length Mean          0
Bwd Packet Length Std           0
Flow Packets/s                  0
Flow IAT Mean                   0
Flow IAT Std                    0
Flow IAT Max                    0
Flow IAT Min                    0
Fwd IAT Total                   0
Fwd IAT Mean                    0
Fwd IAT Std                     0
Fwd IAT Max                     0
Fwd IAT Min                     0
Bwd IAT Total                   0
Bwd IAT Mean                    0
Bwd IAT Std                     0
Bwd IAT Max                     0
Bwd IAT Min                     0
Fwd PSH Flags                   0
Bwd PSH Flags                   0
Fwd URG Flags                   0
Bwd URG Flags                   0
Fwd Header Length               0
Bwd Header Length               0
Fwd Packets/s                   0
Bwd Packets/s                   0
Min Packet Length               0
Max Packet Length               0
Packet Length Mean              0
Packet Length Std               0
Packet Length Variance          0
FIN Flag Count                  0
SYN Flag Count                  0
RST Flag Count                  0
PSH Flag Count                  0
ACK Flag Count                  0
URG Flag Count                  0
CWE Flag Count                  0
ECE Flag Count                  0
Down/Up Ratio                   0
Average Packet Size             0
Avg Fwd Segment Size            0
Avg Bwd Segment Size            0
Fwd Header Length.1             0
Fwd Avg Bytes/Bulk              0
Fwd Avg Packets/Bulk            0
Fwd Avg Bulk Rate               0
Bwd Avg Bytes/Bulk              0
Bwd Avg Packets/Bulk            0
Bwd Avg Bulk Rate               0
Subflow Fwd Packets             0
Subflow Fwd Bytes               0
Subflow Bwd Packets             0
Subflow Bwd Bytes               0
Init_Win_bytes_forward          0
Init_Win_bytes_backward         0
act_data_pkt_fwd                0
min_seg_size_forward            0
Active Mean                     0
Active Std                      0
Active Max                      0
Active Min                      0
Idle Mean                       0
Idle Std                        0
Idle Max                        0
Idle Min                        0
Label                           0
dtype: int64

In [84]:
friday_portscan.isnull().sum().sort_values(ascending=False)

Flow Bytes/s                   15
Flow Duration                   0
Destination Port                0
Total Backward Packets          0
Total Length of Fwd Packets     0
Total Length of Bwd Packets     0
Total Fwd Packets               0
Fwd Packet Length Max           0
Fwd Packet Length Min           0
Fwd Packet Length Std           0
Fwd Packet Length Mean          0
Bwd Packet Length Max           0
Bwd Packet Length Min           0
Bwd Packet Length Mean          0
Bwd Packet Length Std           0
Flow Packets/s                  0
Flow IAT Mean                   0
Flow IAT Std                    0
Flow IAT Max                    0
Flow IAT Min                    0
Fwd IAT Total                   0
Fwd IAT Mean                    0
Fwd IAT Std                     0
Fwd IAT Max                     0
Fwd IAT Min                     0
Bwd IAT Total                   0
Bwd IAT Mean                    0
Bwd IAT Std                     0
Bwd IAT Max                     0
Bwd IAT Min                     0
Fwd PSH Flags                   0
Bwd PSH Flags                   0
Fwd URG Flags                   0
Bwd URG Flags                   0
Fwd Header Length               0
Bwd Header Length               0
Fwd Packets/s                   0
Bwd Packets/s                   0
Min Packet Length               0
Max Packet Length               0
Packet Length Mean              0
Packet Length Std               0
Packet Length Variance          0
FIN Flag Count                  0
SYN Flag Count                  0
RST Flag Count                  0
PSH Flag Count                  0
ACK Flag Count                  0
URG Flag Count                  0
CWE Flag Count                  0
ECE Flag Count                  0
Down/Up Ratio                   0
Average Packet Size             0
Avg Fwd Segment Size            0
Avg Bwd Segment Size            0
Fwd Header Length.1             0
Fwd Avg Bytes/Bulk              0
Fwd Avg Packets/Bulk            0
Fwd Avg Bulk Rate               0
Bwd Avg Bytes/Bulk              0
Bwd Avg Packets/Bulk            0
Bwd Avg Bulk Rate               0
Subflow Fwd Packets             0
Subflow Fwd Bytes               0
Subflow Bwd Packets             0
Subflow Bwd Bytes               0
Init_Win_bytes_forward          0
Init_Win_bytes_backward         0
act_data_pkt_fwd                0
min_seg_size_forward            0
Active Mean                     0
Active Std                      0
Active Max                      0
Active Min                      0
Idle Mean                       0
Idle Std                        0
Idle Max                        0
Idle Min                        0
Label                           0
dtype: int64

In [85]:
friday_ddos.isnull().sum().sort_values(ascending=False)

Flow Bytes/s                   4
Flow Duration                  0
Destination Port               0
Total Backward Packets         0
Total Length of Fwd Packets    0
Total Length of Bwd Packets    0
Total Fwd Packets              0
Fwd Packet Length Max          0
Fwd Packet Length Min          0
Fwd Packet Length Std          0
Fwd Packet Length Mean         0
Bwd Packet Length Max          0
Bwd Packet Length Min          0
Bwd Packet Length Mean         0
Bwd Packet Length Std          0
Flow Packets/s                 0
Flow IAT Mean                  0
Flow IAT Std                   0
Flow IAT Max                   0
Flow IAT Min                   0
Fwd IAT Total                  0
Fwd IAT Mean                   0
Fwd IAT Std                    0
Fwd IAT Max                    0
Fwd IAT Min                    0
Bwd IAT Total                  0
Bwd IAT Mean                   0
Bwd IAT Std                    0
Bwd IAT Max                    0
Bwd IAT Min                    0
Fwd PSH Flags                  0
Bwd PSH Flags                  0
Fwd URG Flags                  0
Bwd URG Flags                  0
Fwd Header Length              0
Bwd Header Length              0
Fwd Packets/s                  0
Bwd Packets/s                  0
Min Packet Length              0
Max Packet Length              0
Packet Length Mean             0
Packet Length Std              0
Packet Length Variance         0
FIN Flag Count                 0
SYN Flag Count                 0
RST Flag Count                 0
PSH Flag Count                 0
ACK Flag Count                 0
URG Flag Count                 0
CWE Flag Count                 0
ECE Flag Count                 0
Down/Up Ratio                  0
Average Packet Size            0
Avg Fwd Segment Size           0
Avg Bwd Segment Size           0
Fwd Header Length.1            0
Fwd Avg Bytes/Bulk             0
Fwd Avg Packets/Bulk           0
Fwd Avg Bulk Rate              0
Bwd Avg Bytes/Bulk             0
Bwd Avg Packets/Bulk           0
Bwd Avg Bulk Rate              0
Subflow Fwd Packets            0
Subflow Fwd Bytes              0
Subflow Bwd Packets            0
Subflow Bwd Bytes              0
Init_Win_bytes_forward         0
Init_Win_bytes_backward        0
act_data_pkt_fwd               0
min_seg_size_forward           0
Active Mean                    0
Active Std                     0
Active Max                     0
Active Min                     0
Idle Mean                      0
Idle Std                       0
Idle Max                       0
Idle Min                       0
Label                          0
dtype: int64

In [87]:
friday_morning.duplicated().sum()

np.int64(6888)

In [88]:
friday_portscan.duplicated().sum()

np.int64(72353)

In [89]:
friday_ddos.duplicated().sum()

np.int64(2633)

In [91]:
np.isinf(
    friday_morning.select_dtypes(include=np.number)
).sum()

Destination Port                 0
Flow Duration                    0
Total Fwd Packets                0
Total Backward Packets           0
Total Length of Fwd Packets      0
Total Length of Bwd Packets      0
Fwd Packet Length Max            0
Fwd Packet Length Min            0
Fwd Packet Length Mean           0
Fwd Packet Length Std            0
Bwd Packet Length Max            0
Bwd Packet Length Min            0
Bwd Packet Length Mean           0
Bwd Packet Length Std            0
Flow Bytes/s                    94
Flow Packets/s                 122
Flow IAT Mean                    0
Flow IAT Std                     0
Flow IAT Max                     0
Flow IAT Min                     0
Fwd IAT Total                    0
Fwd IAT Mean                     0
Fwd IAT Std                      0
Fwd IAT Max                      0
Fwd IAT Min                      0
Bwd IAT Total                    0
Bwd IAT Mean                     0
Bwd IAT Std                      0
Bwd IAT Max                      0
Bwd IAT Min                      0
Fwd PSH Flags                    0
Bwd PSH Flags                    0
Fwd URG Flags                    0
Bwd URG Flags                    0
Fwd Header Length                0
Bwd Header Length                0
Fwd Packets/s                    0
Bwd Packets/s                    0
Min Packet Length                0
Max Packet Length                0
Packet Length Mean               0
Packet Length Std                0
Packet Length Variance           0
FIN Flag Count                   0
SYN Flag Count                   0
RST Flag Count                   0
PSH Flag Count                   0
ACK Flag Count                   0
URG Flag Count                   0
CWE Flag Count                   0
ECE Flag Count                   0
Down/Up Ratio                    0
Average Packet Size              0
Avg Fwd Segment Size             0
Avg Bwd Segment Size             0
Fwd Header Length.1              0
Fwd Avg Bytes/Bulk               0
Fwd Avg Packets/Bulk             0
Fwd Avg Bulk Rate                0
Bwd Avg Bytes/Bulk               0
Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                0
Subflow Fwd Packets              0
Subflow Fwd Bytes                0
Subflow Bwd Packets              0
Subflow Bwd Bytes                0
Init_Win_bytes_forward           0
Init_Win_bytes_backward          0
act_data_pkt_fwd                 0
min_seg_size_forward             0
Active Mean                      0
Active Std                       0
Active Max                       0
Active Min                       0
Idle Mean                        0
Idle Std                         0
Idle Max                         0
Idle Min                         0
dtype: int64

In [92]:
np.isinf(
    friday_portscan.select_dtypes(include=np.number)
).sum()

Destination Port                 0
Flow Duration                    0
Total Fwd Packets                0
Total Backward Packets           0
Total Length of Fwd Packets      0
Total Length of Bwd Packets      0
Fwd Packet Length Max            0
Fwd Packet Length Min            0
Fwd Packet Length Mean           0
Fwd Packet Length Std            0
Bwd Packet Length Max            0
Bwd Packet Length Min            0
Bwd Packet Length Mean           0
Bwd Packet Length Std            0
Flow Bytes/s                   356
Flow Packets/s                 371
Flow IAT Mean                    0
Flow IAT Std                     0
Flow IAT Max                     0
Flow IAT Min                     0
Fwd IAT Total                    0
Fwd IAT Mean                     0
Fwd IAT Std                      0
Fwd IAT Max                      0
Fwd IAT Min                      0
Bwd IAT Total                    0
Bwd IAT Mean                     0
Bwd IAT Std                      0
Bwd IAT Max                      0
Bwd IAT Min                      0
Fwd PSH Flags                    0
Bwd PSH Flags                    0
Fwd URG Flags                    0
Bwd URG Flags                    0
Fwd Header Length                0
Bwd Header Length                0
Fwd Packets/s                    0
Bwd Packets/s                    0
Min Packet Length                0
Max Packet Length                0
Packet Length Mean               0
Packet Length Std                0
Packet Length Variance           0
FIN Flag Count                   0
SYN Flag Count                   0
RST Flag Count                   0
PSH Flag Count                   0
ACK Flag Count                   0
URG Flag Count                   0
CWE Flag Count                   0
ECE Flag Count                   0
Down/Up Ratio                    0
Average Packet Size              0
Avg Fwd Segment Size             0
Avg Bwd Segment Size             0
Fwd Header Length.1              0
Fwd Avg Bytes/Bulk               0
Fwd Avg Packets/Bulk             0
Fwd Avg Bulk Rate                0
Bwd Avg Bytes/Bulk               0
Bwd Avg Packets/Bulk             0
Bwd Avg Bulk Rate                0
Subflow Fwd Packets              0
Subflow Fwd Bytes                0
Subflow Bwd Packets              0
Subflow Bwd Bytes                0
Init_Win_bytes_forward           0
Init_Win_bytes_backward          0
act_data_pkt_fwd                 0
min_seg_size_forward             0
Active Mean                      0
Active Std                       0
Active Max                       0
Active Min                       0
Idle Mean                        0
Idle Std                         0
Idle Max                         0
Idle Min                         0
dtype: int64

In [93]:
np.isinf(
    friday_ddos.select_dtypes(include=np.number)
).sum()

Destination Port                0
Flow Duration                   0
Total Fwd Packets               0
Total Backward Packets          0
Total Length of Fwd Packets     0
Total Length of Bwd Packets     0
Fwd Packet Length Max           0
Fwd Packet Length Min           0
Fwd Packet Length Mean          0
Fwd Packet Length Std           0
Bwd Packet Length Max           0
Bwd Packet Length Min           0
Bwd Packet Length Mean          0
Bwd Packet Length Std           0
Flow Bytes/s                   30
Flow Packets/s                 34
Flow IAT Mean                   0
Flow IAT Std                    0
Flow IAT Max                    0
Flow IAT Min                    0
Fwd IAT Total                   0
Fwd IAT Mean                    0
Fwd IAT Std                     0
Fwd IAT Max                     0
Fwd IAT Min                     0
Bwd IAT Total                   0
Bwd IAT Mean                    0
Bwd IAT Std                     0
Bwd IAT Max                     0
Bwd IAT Min                     0
Fwd PSH Flags                   0
Bwd PSH Flags                   0
Fwd URG Flags                   0
Bwd URG Flags                   0
Fwd Header Length               0
Bwd Header Length               0
Fwd Packets/s                   0
Bwd Packets/s                   0
Min Packet Length               0
Max Packet Length               0
Packet Length Mean              0
Packet Length Std               0
Packet Length Variance          0
FIN Flag Count                  0
SYN Flag Count                  0
RST Flag Count                  0
PSH Flag Count                  0
ACK Flag Count                  0
URG Flag Count                  0
CWE Flag Count                  0
ECE Flag Count                  0
Down/Up Ratio                   0
Average Packet Size             0
Avg Fwd Segment Size            0
Avg Bwd Segment Size            0
Fwd Header Length.1             0
Fwd Avg Bytes/Bulk              0
Fwd Avg Packets/Bulk            0
Fwd Avg Bulk Rate               0
Bwd Avg Bytes/Bulk              0
Bwd Avg Packets/Bulk            0
Bwd Avg Bulk Rate               0
Subflow Fwd Packets             0
Subflow Fwd Bytes               0
Subflow Bwd Packets             0
Subflow Bwd Bytes               0
Init_Win_bytes_forward          0
Init_Win_bytes_backward         0
act_data_pkt_fwd                0
min_seg_size_forward            0
Active Mean                     0
Active Std                      0
Active Max                      0
Active Min                      0
Idle Mean                       0
Idle Std                        0
Idle Max                        0
Idle Min                        0
dtype: int64

In [94]:
friday_morning.replace(
    [np.inf, -np.inf],
    np.nan,
    inplace=True
)

friday_morning.dropna(inplace=True)

friday_morning.drop_duplicates(inplace=True)

In [95]:
friday_portscan.replace(
    [np.inf, -np.inf],
    np.nan,
    inplace=True
)

friday_portscan.dropna(inplace=True)

friday_portscan.drop_duplicates(inplace=True)

In [96]:
friday_ddos.replace(
    [np.inf, -np.inf],
    np.nan,
    inplace=True
)

friday_ddos.dropna(inplace=True)

friday_ddos.drop_duplicates(inplace=True)

In [100]:
print(friday_morning.shape)
print(friday_morning.isnull().sum().sum())
print(friday_morning.duplicated().sum())

(184044, 79)
0
0

In [101]:
print(friday_portscan.shape)
print(friday_portscan.isnull().sum().sum())
print(friday_portscan.duplicated().sum())

(213777, 79)
0
0

In [102]:
print(friday_ddos.shape)
print(friday_ddos.isnull().sum().sum())
print(friday_ddos.duplicated().sum())

(223082, 79)
0
0

In [103]:
friday = pd.concat(
    [friday_morning, friday_portscan, friday_ddos],
    ignore_index=True
)

In [104]:
friday.shape

(620903, 79)

In [105]:
friday['Label'].value_counts()

Label
BENIGN      400247
DDoS        128014
PortScan     90694
Bot           1948
Name: count, dtype: int64

In [106]:
print(monday.columns.equals(tuesday.columns))
print(tuesday.columns.equals(wednesday.columns))
print(wednesday.columns.equals(thursday.columns))
print(thursday.columns.equals(friday.columns))

True
True
True
True

In [107]:
df = pd.concat(
    [
        monday,
        tuesday,
        wednesday,
        thursday,
        friday
    ],
    ignore_index=True
)

In [108]:
df.shape

(2572917, 79)

In [109]:
df['Label'].value_counts()

Label
BENIGN                        2147176
DoS Hulk                       172846
DDoS                           128014
PortScan                        90694
DoS GoldenEye                   10286
FTP-Patator                      5931
DoS slowloris                    5385
DoS Slowhttptest                 5228
SSH-Patator                      3219
Bot                              1948
Web Attack � Brute Force         1470
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64