In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    r"D:\MLOPS\data\processed\cleaned_cicids2017.csv"
)

In [3]:
df.shape

(2572492, 68)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2572492 entries, 0 to 2572491
Data columns (total 68 columns):
 #   Column                       Dtype
---  ------                       -----
 0   Destination Port             int64
 1   Flow Duration                int64
 2   Total Fwd Packets            int64
 3   Total Backward Packets       int64
 4   Total Length of Fwd Packets  int64
 5   Total Length of Bwd Packets  int64
 6   Fwd Packet Length Max        int64
 7   Fwd Packet Length Min        int64
 8   Fwd Packet Length Mean       float64
 9   Fwd Packet Length Std        float64
 10  Bwd Packet Length Max        int64
 11  Bwd Packet Length Min        int64
 12  Bwd Packet Length Mean       float64
 13  Bwd Packet Length Std        float64
 14  Flow Bytes/s                 float64
 15  Flow Packets/s               float64
 16  Flow IAT Mean                float64
 17  Flow IAT Std                 float64
 18  Flow IAT Max                 int64
 19  Flow IAT Min                 int64
 20  Fwd IAT Total                int64
 21  Fwd IAT Mean                 float64
 22  Fwd IAT Std                  float64
 23  Fwd IAT Max                  int64
 24  Fwd IAT Min                  int64
 25  Bwd IAT Total                int64
 26  Bwd IAT Mean                 float64
 27  Bwd IAT Std                  float64
 28  Bwd IAT Max                  int64
 29  Bwd IAT Min                  int64
 30  Fwd PSH Flags                int64
 31  Fwd URG Flags                int64
 32  Fwd Header Length            int64
 33  Bwd Header Length            int64
 34  Fwd Packets/s                float64
 35  Bwd Packets/s                float64
 36  Min Packet Length            int64
 37  Max Packet Length            int64
 38  Packet Length Mean           float64
 39  Packet Length Std            float64
 40  Packet Length Variance       float64
 41  FIN Flag Count               int64
 42  SYN Flag Count               int64
 43  RST Flag Count               int64
 44  PSH Flag Count               int64
 45  ACK Flag Count               int64
 46  URG Flag Count               int64
 47  CWE Flag Count               int64
 48  ECE Flag Count               int64
 49  Down/Up Ratio                int64
 50  Average Packet Size          float64
 51  Avg Fwd Segment Size         float64
 52  Avg Bwd Segment Size         float64
 53  Subflow Fwd Bytes            int64
 54  Subflow Bwd Bytes            int64
 55  Init_Win_bytes_forward       int64
 56  Init_Win_bytes_backward      int64
 57  act_data_pkt_fwd             int64
 58  min_seg_size_forward         int64
 59  Active Mean                  float64
 60  Active Std                   float64
 61  Active Max                   int64
 62  Active Min                   int64
 63  Idle Mean                    float64
 64  Idle Std                     float64
 65  Idle Max                     int64
 66  Idle Min                     int64
 67  Label                        str
dtypes: float64(24), int64(43), str(1)
memory usage: 1.3 GB

In [5]:
df.describe()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,...,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06,2.572492e+06
mean,8.522623e+03,1.625766e+07,1.011601e+01,1.137086e+01,6.013512e+02,1.778216e+04,2.272724e+02,1.949312e+01,6.291132e+01,7.577945e+01,...,5.908631e+00,2.588886e+01,8.966782e+04,4.524773e+04,1.684773e+05,6.408985e+04,9.149345e+06,5.543410e+05,9.567111e+06,8.713645e+06
std,1.886323e+04,3.495417e+07,7.863985e+02,1.046250e+03,1.048162e+04,2.373961e+06,7.492604e+02,6.038148e+01,1.936728e+02,2.940821e+02,...,6.676048e+02,6.517138e+00,6.793207e+05,4.123257e+05,1.074484e+06,6.045179e+05,2.463187e+07,4.825337e+06,2.539541e+07,2.436494e+07
min,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.300000e+01,2.000000e+02,2.000000e+00,1.000000e+00,1.200000e+01,6.000000e+00,6.000000e+00,0.000000e+00,6.000000e+00,0.000000e+00,...,0.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,8.000000e+01,4.885600e+04,2.000000e+00,2.000000e+00,6.600000e+01,1.520000e+02,4.000000e+01,6.000000e+00,3.600000e+01,0.000000e+00,...,1.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,4.430000e+02,5.225669e+06,5.000000e+00,5.000000e+00,3.250000e+02,8.600000e+02,2.010000e+02,3.700000e+01,5.200000e+01,7.167190e+01,...,3.000000e+00,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,6.553500e+04,1.200000e+08,2.197590e+05,2.919220e+05,1.290000e+07,6.554530e+08,2.482000e+04,2.325000e+03,5.940857e+03,7.125597e+03,...,2.135570e+05,1.380000e+02,1.100000e+08,7.420000e+07,1.100000e+08,1.100000e+08,1.200000e+08,7.690000e+07,1.200000e+08,1.200000e+08

In [6]:
df['Label'].value_counts(normalize=True) * 100

Label
BENIGN                        83.450250
DoS Hulk                       6.719010
DDoS                           4.976264
PortScan                       3.525531
DoS GoldenEye                  0.399846
FTP-Patator                    0.230555
DoS slowloris                  0.209330
DoS Slowhttptest               0.203227
SSH-Patator                    0.125132
Bot                            0.075724
Web Attack - Brute Force       0.057143
Web Attack - XSS               0.025345
Infiltration                   0.001399
Web Attack - Sql Injection     0.000816
Heartbleed                     0.000428
Name: proportion, dtype: float64

In [7]:
(df['Flow Duration'] < 0).sum()

np.int64(0)

In [8]:
(df['min_seg_size_forward'] < 0).sum()

np.int64(0)

In [9]:
constant_cols = [
    col for col in df.columns
    if df[col].nunique() == 1
]

constant_cols

[]

In [10]:
low_variance_cols = []

for col in df.columns:

    top_freq = (
        df[col]
        .value_counts(normalize=True)
        .values[0]
    )

    if top_freq > 0.99:
        low_variance_cols.append(col)

low_variance_cols

['Fwd URG Flags', 'RST Flag Count', 'CWE Flag Count', 'ECE Flag Count']

In [11]:
corr_matrix = df.corr(numeric_only=True)

In [12]:
high_corr = []

corr_matrix = df.corr(numeric_only=True)

for col in corr_matrix.columns:

    for row in corr_matrix.index:

        corr_value = corr_matrix.loc[row, col]

        if row != col and abs(corr_value) > 0.95:

            high_corr.append(
                (row, col, corr_value)
            )

high_corr[:20]

[('Fwd IAT Total', 'Flow Duration', np.float64(0.9985349271465833)),
 ('Total Backward Packets',
  'Total Fwd Packets',
  np.float64(0.9990702331625728)),
 ('Total Length of Bwd Packets',
  'Total Fwd Packets',
  np.float64(0.9969934349268765)),
 ('Fwd Header Length', 'Total Fwd Packets', np.float64(0.9994902763436331)),
 ('Bwd Header Length', 'Total Fwd Packets', np.float64(0.9983951916762733)),
 ('Subflow Bwd Bytes', 'Total Fwd Packets', np.float64(0.9969872915383037)),
 ('Total Fwd Packets',
  'Total Backward Packets',
  np.float64(0.9990702331625728)),
 ('Total Length of Bwd Packets',
  'Total Backward Packets',
  np.float64(0.9944296171722797)),
 ('Fwd Header Length',
  'Total Backward Packets',
  np.float64(0.9987781966816165)),
 ('Bwd Header Length',
  'Total Backward Packets',
  np.float64(0.9995618565462628)),
 ('Subflow Bwd Bytes',
  'Total Backward Packets',
  np.float64(0.9944244393202086)),
 ('Subflow Fwd Bytes',
  'Total Length of Fwd Packets',
  np.float64(0.999999358131773)),
 ('Total Fwd Packets',
  'Total Length of Bwd Packets',
  np.float64(0.9969934349268765)),
 ('Total Backward Packets',
  'Total Length of Bwd Packets',
  np.float64(0.9944296171722797)),
 ('Fwd Header Length',
  'Total Length of Bwd Packets',
  np.float64(0.9958419710248387)),
 ('Bwd Header Length',
  'Total Length of Bwd Packets',
  np.float64(0.9938610717011807)),
 ('Subflow Bwd Bytes',
  'Total Length of Bwd Packets',
  np.float64(0.999999860133793)),
 ('Fwd Packet Length Std',
  'Fwd Packet Length Max',
  np.float64(0.9685532417150144)),
 ('Avg Fwd Segment Size', 'Fwd Packet Length Mean', np.float64(1.0)),
 ('Fwd Packet Length Max',
  'Fwd Packet Length Std',
  np.float64(0.9685532417150144))]

In [14]:
df['Binary_Label'] = df['Label'].apply(
    lambda x: 0 if x == 'BENIGN' else 1
)

In [15]:
df['Binary_Label'].value_counts()

Binary_Label
0    2146751
1     425741
Name: count, dtype: int64

In [16]:
df['Binary_Label'].value_counts(normalize=True) * 100

Binary_Label
0    83.45025
1    16.54975
Name: proportion, dtype: float64

In [17]:
X = df.drop(
    columns=['Label', 'Binary_Label']
)

In [18]:
y = df['Binary_Label']

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [21]:
y_train.value_counts(normalize=True) * 100

Binary_Label
0    83.450235
1    16.549765
Name: proportion, dtype: float64

In [22]:
y_test.value_counts(normalize=True) * 100

Binary_Label
0    83.450308
1    16.549692
Name: proportion, dtype: float64

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score
)

In [25]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

In [26]:
rf.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [27]:
y_pred = rf.predict(X_test)

In [28]:
accuracy_score(y_test, y_pred)

0.9986297349460349

In [29]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    429351
           1       1.00      1.00      1.00     85148

    accuracy                           1.00    514499
   macro avg       1.00      1.00      1.00    514499
weighted avg       1.00      1.00      1.00    514499

In [30]:
confusion_matrix(y_test, y_pred)

array([[429060,    291],
       [   414,  84734]])

In [31]:
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
})

In [32]:
feature_importance.sort_values(
    by='Importance',
    ascending=False
).head(20)

                        Feature  Importance
13        Bwd Packet Length Std    0.096463
39            Packet Length Std    0.078431
52         Avg Bwd Segment Size    0.054072
12       Bwd Packet Length Mean    0.053461
10        Bwd Packet Length Max    0.046958
40       Packet Length Variance    0.045995
50          Average Packet Size    0.044217
54            Subflow Bwd Bytes    0.035516
0              Destination Port    0.033538
2             Total Fwd Packets    0.031012
38           Packet Length Mean    0.028871
53            Subflow Fwd Bytes    0.027495
5   Total Length of Bwd Packets    0.022588
4   Total Length of Fwd Packets    0.021529
32            Fwd Header Length    0.020624
37            Max Packet Length    0.016726
6         Fwd Packet Length Max    0.016000
58         min_seg_size_forward    0.015054
44               PSH Flag Count    0.014965
35                Bwd Packets/s    0.014872